### ISSUE TITLE
Problem with proof verification interface?

### ISSUE THREAD

**Issue by LStella** [opentimestamps/opentimestamps.org#20] opened 2017-10-03 21:12 UTC
It seems that either there has been some modification of the proof verification interface or there is a bug. I am verifiying a proof and when verifying the counter goes to "100%" but I don't see the "Success! Bitcoin attests data existed as of [Date and time your order was created] GMT-0400 (Eastern Daylight Time)" like there used to be. See: 

![image](https://user-images.githubusercontent.com/10980189/31149456-f87b2af4-a85d-11e7-836f-d73691119101.png)

**Comment by RCasatta** [comment] 2017-10-04 09:04
Hello, I can't emulate the error.

Which browser do you use ? [compatibility list](https://github.com/opentimestamps/javascript-
opentimestamps#browser-1)

Is your Internet connection good ? Browser verification works by asking full blocks to various blockexplorer, this could be up to 1MB repeated up to 4 block explorers

Could also be a temporary issue with block explorers, in that case retry later, or if you have bitcoin node you can try with the command line tools like the pythone [one](https://github.com/opentimestamps/opentimestamps-client)

If you still have problems you can help us by sharing your file and timestamped receipt if there aren't privacy issue or share the console output of the browser (if you use chrome search for "Developer tools")

**Comment by LStella** [comment] 2017-10-04 14:01
This is a video of the error: https://youtu.be/lp5AIJiOaTc

Browser: 60.0.3112.113 (Official Build) (64-bit)

(This HAS worked before on this browser and this machine in the past, perhaps a few months ago)

I've retried now and still the same problem, both on Chrome and on Brave Browser. I have not tried Firefox or Safari.

It's not urgent, I am doing some testing for the Bylls OTS integration. We wanted to use the opentimestamps site for users to use a 3rd party hosted verification service.

**Comment by RCasatta** [comment] 2017-10-04 14:26
Could you please  share the .ots file?

**Comment by FrancisPouliot** [comment] 2017-11-14 17:39
Still same error happening on different machine, with different files.

**Comment by RCasatta** [comment] 2018-02-16 11:41
We cannot reproduce this error when @LStella was here, since there are any updates I am going to close this. Feel free to comment with new evidence, we will reopen this

**Closed by RCasatta** 2018-02-16 11:41 UTC
